version: '3.8'

services:
  airconnect-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airconnect-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - "SERVER_PORT=${PORT}"
      - "SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
      - "SPRING_DATASOURCE_USERNAME=${DB_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}"
      - "SPRING_DATA_REDIS_HOST=redis"
      - "SPRING_DATA_REDIS_PORT=6379"
      - "SPRING_DATA_REDIS_URL=redis://redis:6379"
      - "JWT_SECRET=${JWT_SECRET}"
      - "APPLE_TEAM_ID=${TEAM_ID}"
      - "APPLE_KEY_ID=${KEY_ID}"
      - "APPLE_BUNDLE_ID=${BUNDLE_ID}"
      - "APPLE_KEY_PATH=${KEY_PATH}"
      - "PROFILE_IMAGE_URL_BASE=${PROFILE_IMAGE_URL_BASE}"
      - "PROFILE_IMAGE_PATH=${APP_UPLOAD_PROFILE_IMAGE_DIR}"
    volumes:
      - "./profile-images:${APP_UPLOAD_PROFILE_IMAGE_DIR}"
      - "./logs:/app/logs"
      - "./src/main/resources/key:/app/key"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - airconnect-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: airconnect-mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - "MYSQL_DATABASE=${DB_NAME}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
      - "TZ=Asia/Seoul"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    networks:
      - airconnect-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: redis:7.2-alpine
    container_name: airconnect-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - "./redis-data:/data"
    networks:
      - airconnect-network
    restart: always

networks:
  airconnect-network:
    driver: bridge