package univ.airconnect.iap.domain;

public enum LedgerRefType {
    IAP_ORDER,
    IAP_REFUND,
    AD_REWARD_SESSION,
    MATCHING_RECOMMENDATION,
    MATCHING_CONNECT,
    GROUP_MATCHING,
    MILESTONE_REWARD,
    ADMIN_ADJUSTMENT,
    FESTIVAL_COUPON,
    REFERRAL_REWARD
}
