package univ.airconnect.admin;

public enum AdminAuditAction {
    DASHBOARD_VIEWED,
    OUTBOX_MONITOR_VIEWED,
    MATCHING_FUNNEL_VIEWED,
    INTEGRITY_CHECK_VIEWED,
    USER_ACTION_APPLIED,
    REPORT_STATUS_UPDATED,
    TICKET_ADJUSTED,
    NOTICE_BROADCASTED,
    MAINTENANCE_UPDATED
}
