package univ.airconnect.admin;

public enum AdminAuditAction {
    ADMIN_API_CALLED,
    DASHBOARD_VIEWED,
    OPERATIONS_SUMMARY_VIEWED,
    API_USAGE_VIEWED,
    OUTBOX_MONITOR_VIEWED,
    OUTBOX_RETRY_QUEUED,
    INTEGRITY_ISSUES_VIEWED,
    MATCHING_FUNNEL_VIEWED,
    GROUP_MATCHING_FUNNEL_VIEWED,
    NOTIFICATION_OPERATIONS_VIEWED,
    OPERATIONS_MANAGEMENT_VIEWED,
    INTEGRITY_CHECK_VIEWED,
    USER_ACTION_APPLIED,
    USER_PERMANENTLY_DELETED,
    REPORT_STATUS_UPDATED,
    TICKET_ADJUSTED,
    NOTICE_BROADCASTED,
    MAINTENANCE_UPDATED,
    CHAT_MESSAGES_INSPECTED
}
